on:
  push:
    branches: ["**"]
  # Allows to trigger the workflow manually

jobs:
  TestGeokitDevLocal:
    name: Test local development Version on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest"]
        os: ["ubuntu-latest"]
        scipy_version: ["11.4", "1.8.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: reskit_env
          conda-remove-defaults: true
      - name: Run tests
        shell: pwsh
        run: |
          ls
          echo "LS Done"
          mamba create --name reskit_env scipy=${{ matrix.scipy_version }} pandas
          echo "Installation done"
          mamba list --name reskit_env
          echo "libaries printed"
          echo "start pytest"
          mamba run --name reskit_env python min_test.py
