on:
  push:
    branches: ["**"]
  # Allows to trigger the workflow manually

jobs:
  TestGeokitDevLocal:
    name: scipy=${{ matrix.scipy_version }} os=${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        # os: ["ubuntu-latest"]
        scipy_version:
          [
            "1.5.2",
            "1.5.3",
            "1.6.0",
            "1.6.1",
            "1.6.2",
            "1.6.3",
            "1.7.0",
            "1.7.1",
            "1.7.2",
            "1.7.3",
            "1.8.0",
            "1.8.1",
            "1.9.0",
            "1.9.1",
            "1.9.2",
            "1.9.3",
            "1.10.0",
            "1.10.1",
            "1.11.0",
            "1.11.1",
            "1.11.2",
            "1.11.3",
            "1.11.4",
            "1.12.0",
            "1.13.0",
            "1.13.1",
            "1.14.0",
            "1.14.1",
            "1.15.0",
            "1.15.1",
            "1.15.2",
            "1.16.0",
            "1.16.1",
            "1.16.2",
            "1.16.3",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: reskit_env
          conda-remove-defaults: true
      - name: Run tests
        shell: pwsh
        run: |
          ls
          echo "LS Done"
          mamba create --name reskit_env scipy=${{ matrix.scipy_version }} pandas openpyxl
          echo "Installation done"
          mamba list --name reskit_env
          echo "libaries printed"
          echo "start pytest"
          mamba run --name reskit_env python test_regular_grid.py
          # mamba run --name reskit_env python test_linear_nd_Interpolator.py
          # mamba run --name reskit_env python grid_data_os_inconsistency_test.py
          # mamba run --name reskit_env python test_scipy_example/test_scipy_example.py
